site_name: Como usar Player/Stage
repo_url: https://github.com/NickelsLab/Player-Stage-Manual
theme: readthedocs
pages:
- Home : index.md
- 'Ch1 - Introducao': 'INTRO.md'
- 'Ch2 - O Basico': 'BASICS.md'
- 'Cap3 - Construindo um mundo': 'WORLDFILES.rst'
- 'Ch4 - Writing a Configuration (.cfg) File': 'CFGFILES.md'
- 'Ch5 - Getting Your Simulation to Run your code': 'CONTROLLERS.md'
- 'Ch6 - Controllers (C++)': 'CONTROLLER_CPP.md'
- 'Ch7 - Controllers (C)': 'CONTROLLER_C.md'
- 'Ch8 - Controllers (Python/playercpp)': 'CONTROLLER_PYCPP.md'
- 'Ch9 - Controllers (Python/playerc)': 'CONTROLLER_PYC.md'
- 'Ch10 - Building a New Interface': 'INTERFACES.md'
- 'Ch11 - Building a New Driver': 'DRIVERS.md'

markdown_extensions:
- toc:
    permalink: True
